### ISSUE TITLE
np.round returns incorrect results

### ISSUE THREAD

**Issue by ghost** [isuruf/flang#103] opened 2017-12-31 06:07 UTC
In order to debug compiler failures, I will be building SciPy and NumPy against the reference LAPACK because OpenBLAS is too difficult to debug. This is the first of these issues.

For the released numpy:

```
In [9]: np.rint(4.5)
Out[9]: 4.0
```

When compiled with the reference LAPACK:

```
In [4]: np.rint(4.5)
Out[4]: 5.0
```

**Comment by isuruf** [comment] 2017-12-31 07:48
In the reference case `mean(4,5)==4` and `mean(5,6)==6`. Whereas in Flang, `mean(4,5)==5`.

This seems to be related to the last issue as well.

It seems the default rounding mode of Flang is round up and reference is round to even

**Comment by isuruf** [comment] 2017-12-31 17:32
Can reproduce locally on linux as well.

```
program main
use ieee_arithmetic
  print *, ieee_rint(4.5)
end program main
```

`flang test.f95 && ./a.out` gives 5.0 and
`gfortran test.f95 && ./a.out` gives 4.0

**Comment by xoviat** [comment] 2017-12-31 18:05
Closing in favor of flang-compiler/flang#349.

**Comment by ghost** [comment] 2017-12-31 18:06
Duplicate of flang-compiler/flang#349.

**Closed as completed** 2017-12-31 18:06 UTC
Labels: numpy, lapack
